Update admin dashboard to be more user friendly
trackit/amplify-video-community pull request #28
Opened 2021-08-07 18:36 UTC by florian-vuillemot

![image](https://user-images.githubusercontent.com/16242135/128610653-f44d1a02-3c18-41d0-b8ca-87817711ffbe.png)

2021-08-07 18:39 UTC, florian-vuillemot commented
I didn't use the theme component (`shared/components/theme`), should I?

2021-08-09 11:26 UTC, MarlonLH requested changes
These components aren't designed for an admin panel, so they won't render well anyway.
Please keep a consistent color to prevent a high color complexity.

2021-08-09 11:26 UTC, MarlonLH commented on src/pages/admin/index.tsx
> +    color: ${(props) => props.color || '#000000'};
Keep the same color for all the titles.

```suggestion
    color: #000000;
```

2021-08-09 11:26 UTC, MarlonLH commented on src/pages/admin/index.tsx
> +    font-size: 48px;
Decrease the text size
```suggestion
    font-size: 38px;
```

2021-08-09 11:26 UTC, MarlonLH commented on src/pages/admin/index.tsx
> +            color="#ff9900"
Keep it black

```suggestion
            color="#000000"
```

2021-08-09 11:26 UTC, MarlonLH commented on src/pages/admin/index.tsx
> +            color="#ff9900"
Keep it black

```suggestion
            color="#000000"
```

2021-08-09 11:26 UTC, MarlonLH commented on src/pages/admin/index.tsx
> +            color="#ff9900"
Keep it black

```suggestion
            color="#000000"
```

2021-08-09 11:26 UTC, MarlonLH commented on src/pages/admin/index.tsx
> +            color="#ff9900"
Keep it black

```suggestion
            color="#000000"
```

2021-08-09 11:26 UTC, MarlonLH commented on src/pages/admin/index.tsx
> +            icon={FcEnteringHeavenAlive}
Keep the same icon

```suggestion
            icon={SiGoogletagmanager}
```

2021-08-09 11:26 UTC, MarlonLH commented on src/pages/admin/index.tsx
> +            icon={FaUserFriends}
Keep the same icon

```suggestion
            icon={SiGoogletagmanager}
```

2021-08-09 17:12 UTC, florian-vuillemot commented
![image](https://user-images.githubusercontent.com/16242135/128746346-8dcb1e50-fbf5-4d6e-9afe-ef95483adbb0.png)

2021-08-10 14:18 UTC, MarlonLH approved these changes

2021-08-10 15:04 UTC, merged